version: 1
disable_existing_loggers: False

formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    format: '%(asctime)s %(levelprefix)s [%(name)s] - %(message)s'
  access:
    "()": uvicorn.logging.AccessFormatter
    format: '%(asctime)s %(levelprefix)s [%(client_addr)s] - "%(request_line)s" %(status_code)s'

filters:
  access_filter:
    "()": apprise_api_headless.logging.AccessFilter

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: access
    class: logging.StreamHandler
    stream: ext://sys.stdout
    filters: [access_filter]

loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: no
  uvicorn.error:
    level: INFO
  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: no
  apprise:
    level: INFO
    handlers: [default]
    propagate: no

root:
  level: INFO
  handlers: [default]
